### ISSUE TITLE
Escaped css gets un-escaped

### ISSUE THREAD

**Issue by jsnanigans** [HapLifeMan/purifycss-extended#1]
version 1.3.3

When using a class name that has a character that has to be escaped, for example `class="some@class"` the required css would look like this: `.some\@class` but if i feed that into purifycss it gets un-escaped.

so 
```css
.class\@name {width: 2vw}
```
becomes
```css
.class@name {
  width: 2vw;
}
```
and does not work anymore

here is a example: https://runkit.com/jsnanigans/5a062d8012da6d0012bde28c
