### ISSUE TITLE
Classes that should not be there

### ISSUE THREAD

**Issue by jsnanigans** [HapLifeMan/purifycss-extended#5]
I just found a funny bug that makes almost no sense to me, if you have this html
```html
<div class="some">3</div>
```
and this css:
```css
.some-3 {
    content: 'why is this here?'
}
```
nothing gets removed when you run purifycss,
here is a quick example:
https://runkit.com/jsnanigans/5a0c36df2daf400012bbf5c6
